#!/bin/bash

if [[ $1 == "config" ]]; then
cat <<EOF
graph_title Celery capacity
graph_args --base 1000 -l 0
graph_category celery
graph_order busy
graph_vlabel processes
graph_total total
busy.label busy workers
busy.draw AREA
busy.colour 33cc00
free.label free slots
free.draw STACK
free.colour ccff00
EOF
else
curl -s http://$CELERY_URL/dashboard?json=1  > /tmp/celery.json
FREE_WORKERS=$(cat /tmp/celery.json | jq -r '.data[] | .hostname' | wc -l)
BUSY_WORKERS=$(cat /tmp/celery.json  | jq '.data[] | .active' | awk '{s+=$1} END {print s}')
echo free.value $(( $CELERYD_CONCURRENCY * $FREE_WORKERS - $BUSY_WORKERS ))
echo busy.value $BUSY_WORKERS
rm -f /tmp/celery.json
fi