#!/usr/bin/perl

use strict;
use warnings;

use Munin::Plugin::Pgsql;

my $pg = Munin::Plugin::Pgsql->new(
    basename => 'postgres_activities_',
    title    => 'PostgreSQL Current running queries',
    info     => 'Running queries',
    vlabel   => 'Queries',
    basequery =>
        "SELECT 'queries',count(query) AS queries FROM pg_stat_activity WHERE state = 'active'",
    wildcardfilter => "",
    configquery  => "SELECT 'queries'",
    suggestquery =>
        "SELECT datname FROM pg_database WHERE datallowconn AND NOT datistemplate AND NOT datname='postgres' UNION ALL SELECT 'ALL' ORDER BY 1 LIMIT 10",
    graphdraw => 'AREA',
    stack     => 1,
    base      => 1024
);

$pg->Process();
exit(0);

