#!/usr/bin/perl

use strict;
use warnings;

use Munin::Plugin::Pgsql;

my $pg = Munin::Plugin::Pgsql->new(
    minversion => 8.3,
    basename => 'postgres_activities',
    title    => 'PostgreSQL Current running queries',
    info     => 'Running queries',
    vlabel   => 'Queries',
    basequery => "SELECT 'queries',count(*) AS queries FROM pg_stat_activity WHERE state = 'active'",
    configquery  => "SELECT 'queries','Queries'",
);

$pg->Process();
exit(0);

