#!/bin/sh

ip_socket=$(echo $0 | awk -F_ '{ print $3 }')
if [ $ip_socket = "socket" ]; then
tmp_var=$(echo $0 | awk -F_ '{ s = ""; for (i = 3; i <= NF; i++) s = s $i "/"; print s }')
port_path=$(echo "/${tmp_var}" | sed 's,/$,,')
else
port_path=$(echo $0 | awk -F_ '{ print $4 }')
fi

if [ "$ip_socket" = "socket" ]; then
    ip_socket="-s";
else
    if [ -z $ip_socket ] ; then
      ip_socket="-h 127.0.0.1"
    else
      ip_socket="-h $ip_socket"
    fi
fi

if [ -z "$port_path" ]; then
    port_path="-p 6379"
elif [ "$ip_socket" = "-s" ]; then
    port_path="$port_path"
else
    port_path="-p $port_path"
fi

# add the ability to set a password in a respective config file
if [ -z "$password" ]; then
    passwd='' # no password was configured
else
    passwd="-a $password"
fi


if [ "$1" = "config" ]; then

echo -n "graph_title Redis Queues
graph_args --base 1000 -l 0
graph_category queue
graph_vlabel size
";

for e in $MUNIN_REDIS_QUEUE_CONFIG; do
    echo $e | { IFS=: read RCMD RKEY WARN CRITICAL;
    echo  "$RKEY.label count
$RKEY.warning :$WARN
$RKEY.critical :$CRITICAL
$RKEY.label $RKEY ($RCMD)"
}
done

else
    for e in $MUNIN_REDIS_QUEUE_CONFIG; do
        echo $e | { IFS=: read RCMD RKEY WARN CRITICAL;
        N=`redis-cli $ip_socket $port_path $passwd $RCMD $RKEY`;
        echo  "$RKEY.value $N"; }
    done
fi
